name: KUAHelper
version: '${project.version}'
main: com.lichenaut.kuahelper.KUAHelper
api-version: '1.20'
depend: [Essentials, LuckPerms]
author: lichenaut
description: Plugin for 5kUA's miscellaneous features.
commands:
  vegan:
    description: Vegan mode.
    usage: /vegan [on|off]
  map:
    description: Get the link to the server's map.
    usage: /map
  send:
    description: Send a code to the provided e-mail address.
    usage: /send <e-mail>
  verify:
    description: Verify a code.
    usage: /verify <code>